remote_theme: "mmistakes/so-simple-theme"
baseurl: "/website"
title: "熊猫的日常"
# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml
  
# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true
